import type { StencilSettings } from "./types";

export const DEFAULT_STENCIL_SETTINGS: StencilSettings = {
  visualMode: "diffusion",
  foregroundColor: "#24a326",
  backgroundMode: "white",
  backgroundColor: "#ffffff",
  threshold: 208,
  invert: false,
  textureType: "mixed",
  textureDensity: 0.42,
  textureScale: 34,
  edgeEmphasis: 0.55,
  diffusionStrength: 0.68,
  diffusionLineSpacing: 13,
  diffusionLineWidth: 2.2,
  diffusionDotDensity: 0.38,
  diffusionGrowth: 0.92,
  flowEnabled: true,
  breathingEnabled: true,
  animationDuration: 4,
  frameRate: 24,
  flowSpeed: 0.65,
  breathingAmplitude: 22,
};
